### ISSUE TITLE
init_io crashes on some file handles

### ISSUE THREAD

**Issue by sciurius** [benkasminbullock/image-png-libpng#39] opened 2023-12-24 19:51 UTC
This occurs with several (all?) Perl versions on Linux and Windows.

`init_io` is documented to take an already-opened Perl file handle. For example
````
open( my $file, '<:raw', 'nice.png') or die $!;
$png->init_io ($file);
````
However this crashes with segmentation fault:
````
open( my $file, '<:raw', \$pngdata ) or die $!;
$png->init_io ($file);
````
This fails with "unopened file handle?": 
````
use IO::String;
my $file = IO::String->new($pngdata);
$png->init_io ($file);
````

FYI, I'm aware that there is a `read_from_scalar` function.

**Comment by PhilterPaper** [comment] 2023-12-24 23:10
The same slug of PNG image data (read in-line from an SVG file with an embedded PNG image) fails with 

> Cannot open 'IO::String=GLOB(0x49454b0)' for reading: Invalid argument at ...

in PDF::API2, in the call `$libpng = Image::PNG::Libpng::read_png_file($file);` (the above report by Johan pertains to my PDF::Builder code). The two cases may be related, as the data slug is an IO::String ref, which doesn't seem to be quite the same as an opened filehandle.

**Comment by benkasminbullock** [comment] 2023-12-25 04:00
IPL's "init_io" is a wrapper for "png_init_io" from libpng. Here is the C
source code of png_init_io from libpng:

void PNGAPI
png_init_io(png_structrp png_ptr, png_FILE_p fp)
{
   png_debug(1, "in png_init_io");

   if (png_ptr == NULL)
      return;

   png_ptr->io_ptr = (png_voidp)fp;
}

The png_structrp png_ptr part is $png in the Perl code, and fp is your
scalar.

All it does is to copy a FILE * (the PNG people made a macro called
png_FILE_p to duplicate FILE * although this is 100% standard C) into
"png_ptr->io_ptr".

So we actually do need a C FILE *. If your png data is already in a Perl
scalar then I don't know how to get one from that, or if it is possible.

I couldn't reproduce the segmentation fault for the first one. It appears
to execute and halt without error. Here is the exact code I used:

use lib '/home/ben/projects/image-png-libpng/blib/lib';
use lib '/home/ben/projects/image-png-libpng/blib/arch';
use Image::PNG::Libpng ':all';
my $png = create_read_struct ();
my $pngdata ;
open( my $file, '<:raw', \$pngdata ) or die $!;
$png->init_io ($file);

I also tried initialising $pngdata as an empty string with the same result.

Regarding the second example, I got the same error message. At the moment,
the Image::PNG::Libpng code calls to sv_2io on the scalar, and then uses
the IoIFP macro to get the filehandle (the C FILE *) from that. When it
finds that the filehandle is a NULL pointer, it gives up with the above
error message. I don't know of a way to read from the scalar and turn that
into a FILE * which could be passed into the C code of libpng.

In the meantime I've improved the error message for the function.

**Comment by benkasminbullock** [comment] 2023-12-26 08:03
I've added to the documentation of init_io in commit c073220edc2487ad7fda552674e3ac2b78ce677c. Realistically init_io is a wrapper for the C function png_init_io, and the facility to read from a scalar also exists in the module as noted in the initial bug report. I remember spending quite a long time figuring out how to read a PNG from a non-file source and getting it to work in Perl. I hope the time and effort I spent doing that is useful for someone. Rather than making a very complex addition to init_io to make it able to read from Perl scalars used as file handles, I would prefer to just tell people not to use init_io for this job, so I would like to close this issue. Thank you for reporting.

**Closed by benkasminbullock** 2023-12-26 08:03 UTC

**Comment by PhilterPaper** [comment] 2023-12-26 15:02
We're making good progress on handling this on the PDF::Builder side (handling the various form of filehandles). See sciurius/perl-SVGPDF/issues/2. It looks like nothing needs to be done to IPL to get SVGPDF + PDF::Builder running; presumably similar fixes (for the original reported problem) are needed in PDF::API2 to support SVGPDF, and who knows when that will get done..
